INSERT INTO dogs (breed_id, email, dog_name, owner_first_name, owner_last_name, password, profile_pic_url, birth_date, bio_description, gender, location) VALUES
(2,'m.bednarski@gmail.com','Onix','Matt','Bed','test','https://i.imgur.com/cVXTX9C.jpg','2012-04-12','A puppy at heart. Favourite toy: pink squeaky bone. Favourite food: all of it','f','Toronto, ON, Canada'),
(1,'test@test.com','Doge','John','Doe','test','https://i.kym-cdn.com/entries/icons/mobile/000/013/564/doge.jpg','2016-02-02','DOGE says BORK','u','Toronto, ON, Canada'),
(3,'test1@test.com','Mr Peanut Butter','','','test','https://pyxis.nymag.com/v1/imgs/31e/b17/ad6bd35c8917a66a004ff177c789cdd992-bojack-horseman-13.rsquare.w700.jpg','1969-08-20','Mr. Peanutbutter was my fathers name. AND ITS MY NAME TOO!','m','Toronto, ON, Canada'),
(4,'test2@test.com','Rover','Jane','Janeson','test','https://www.babycenter.com/ims/2015/05/460588321_square.jpg','2019-10-14','BORKBORKBORKBORKBORKBORK','m','Toronto, ON, Canada'),
(4,'test3@test.com','Sydney','','','test','https://www.thesprucepets.com/thmb/AV6s4AL9uAcAobnwz0KdkW2UG08=/1333x1000/smart/filters:no_upscale()/shih-tzu-dog-breed-profile-1117999-hero-5541b7f6f936478ca766d85ff5af202e.jpeg','2010-03-20','Does not like anyone. Probably does not like you.','f','Toronto, ON, Canada'),
(5,'test4@test.com','Stark','E','Chris','test','https://www.loveyourdog.com/wp-content/uploads/2020/04/Siberian-Husky-in-Snow.jpg','2018-07-29','Fierce but playful!','m','Toronto, ON, Canada'),
(6,'test5@test.com','Lily','Olga','P','test','https://www.petlandflorida.com/wp-content/uploads/2021/01/Petland_Florida_Toy_Poodle.jpg','2021-02-14','Playful and energetic!','f','Toronto, ON, Canada'),
(7,'test6@test,com','Sonic','','','test','https://figopetinsurance.com/sites/default/files/imagedogscute-italian-greyhound-sitting-couchblog.jpg','2015-09-12','GOTTA RUN FASTER!','f','Toronto, ON, Canada');
